export const BUSINESS_LIST_REQUEST = "BUSINESS_LIST_REQUEST";
export const BUSINESS_LIST_SUCCESS = "BUSINESS_LIST_SUCCESS";
export const BUSINESS_LIST_FAIL = "BUSINESS_LIST_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";

export const BUSINESS_DELETE_REQUEST = "BUSINESS_DELETE_REQUEST";
export const BUSINESS_DELETE_SUCCESS = "BUSINESS_DELETE_SUCCESS";
export const BUSINESS_DELETE_FAIL = "BUSINESS_DELETE_FAIL";

export const BUSINESS_CREATE_REQUEST = "BUSINESS_CREATE_REQUEST";
export const BUSINESS_CREATE_SUCCESS = "BUSINESS_CREATE_SUCCESS";
export const BUSINESS_CREATE_FAIL = "BUSINESS_CREATE_FAIL";
export const BUSINESS_CREATE_RESET = "BUSINESS_CREATE_RESET";

export const BUSINESS_UPDATE_REQUEST = "BUSINESS_UPDATE_REQUEST";
export const BUSINESS_UPDATE_SUCCESS = "BUSINESS_UPDATE_SUCCESS";
export const BUSINESS_UPDATE_FAIL = "BUSINESS_UPDATE_FAIL";
export const BUSINESS_UPDATE_RESET = "BUSINESS_UPDATE_RESET";
