export const FUNDS_LIST_REQUEST = "FUNDS_LIST_REQUEST";
export const FUNDS_LIST_SUCCESS = "FUNDS_LIST_SUCCESS";
export const FUNDS_LIST_FAIL = "FUNDS_LIST_FAIL";


export const FUNDS_DELETE_REQUEST = "FUNDS_DELETE_REQUEST";
export const FUNDS_DELETE_SUCCESS = "FUNDS_DELETE_SUCCESS";
export const FUNDS_DELETE_FAIL = "FUNDS_DELETE_FAIL";

export const FUNDS_CREATE_REQUEST = "FUNDS_CREATE_REQUEST";
export const FUNDS_CREATE_SUCCESS = "FUNDS_CREATE_SUCCESS";
export const FUNDS_CREATE_FAIL = "FUNDS_CREATE_FAIL";
export const FUNDS_CREATE_RESET = "FUNDS_CREATE_RESET";

