export const SELL_PORTFOLIO_LIST_REQUEST = "SELL_PORTFOLIO_LIST_REQUEST";
export const SELL_PORTFOLIO_LIST_SUCCESS = "SELL_PORTFOLIO_LIST_SUCCESS";
export const SELL_PORTFOLIO_LIST_FAIL = "SELL_PORTFOLIO_LIST_FAIL";

export const SELL_PORTFOLIO_LIST_BY_CLIENT_ID_REQUEST =
  "SELL_PORTFOLIO_LIST_BY_CLIENT_ID_REQUEST";
export const SELL_PORTFOLIO_LIST_BY_CLIENT_ID_SUCCESS =
  "SELL_PORTFOLIO_LIST_BY_CLIENT_ID_SUCCESS";
export const SELL_PORTFOLIO_LIST_BY_CLIENT_ID_FAIL =
  "SELL_PORTFOLIO_LIST_BY_CLIENT_ID_FAIL";

export const SELL_PORTFOLIO_DETAILS_REQUEST = "SELL_PORTFOLIO_DETAILS_REQUEST";
export const SELL_PORTFOLIO_DETAILS_SUCCESS = "SELL_PORTFOLIO_DETAILS_SUCCESS";
export const SELL_PORTFOLIO_DETAILS_FAIL = "SELL_PORTFOLIO_DETAILS_FAIL";

export const SELL_PORTFOLIO_DELETE_REQUEST = "SELL_PORTFOLIO_DELETE_REQUEST";
export const SELL_PORTFOLIO_DELETE_SUCCESS = "SELL_PORTFOLIO_DELETE_SUCCESS";
export const SELL_PORTFOLIO_DELETE_FAIL = "SELL_PORTFOLIO_DELETE_FAIL";

export const SELL_PORTFOLIO_CREATE_REQUEST = "SELL_PORTFOLIO_CREATE_REQUEST";
export const SELL_PORTFOLIO_CREATE_SUCCESS = "SELL_PORTFOLIO_CREATE_SUCCESS";
export const SELL_PORTFOLIO_CREATE_FAIL = "SELL_PORTFOLIO_CREATE_FAIL";
export const SELL_PORTFOLIO_CREATE_RESET = "SELL_PORTFOLIO_CREATE_RESET";

export const SELL_PORTFOLIO_UPDATE_REQUEST = "SELL_PORTFOLIO_UPDATE_REQUEST";
export const SELL_PORTFOLIO_UPDATE_SUCCESS = "SELL_PORTFOLIO_UPDATE_SUCCESS";
export const SELL_PORTFOLIO_UPDATE_FAIL = "SELL_PORTFOLIO_UPDATE_FAIL";
export const SELL_PORTFOLIO_UPDATE_RESET = "SELL_PORTFOLIO_UPDATE_RESET";
