export const WITHDRAW_FUNDS_LIST_REQUEST = "WITHDRAW_FUNDS_LIST_REQUEST";
export const WITHDRAW_FUNDS_LIST_SUCCESS = "WITHDRAW_FUNDS_LIST_SUCCESS";
export const WITHDRAW_FUNDS_LIST_FAIL = "WITHDRAW_FUNDS_LIST_FAIL";


export const WITHDRAW_FUNDS_DELETE_REQUEST = "WITHDRAW_FUNDS_DELETE_REQUEST";
export const WITHDRAW_FUNDS_DELETE_SUCCESS = "WITHDRAW_FUNDS_DELETE_SUCCESS";
export const WITHDRAW_FUNDS_DELETE_FAIL = "WITHDRAW_FUNDS_DELETE_FAIL";

export const WITHDRAW_FUNDS_CREATE_REQUEST = "WITHDRAW_FUNDS_CREATE_REQUEST";
export const WITHDRAW_FUNDS_CREATE_SUCCESS = "WITHDRAW_FUNDS_CREATE_SUCCESS";
export const WITHDRAW_FUNDS_CREATE_FAIL = "WITHDRAW_FUNDS_CREATE_FAIL";
export const WITHDRAW_FUNDS_CREATE_RESET = "WITHDRAW_FUNDS_CREATE_RESET";

